version: '3.8'

services:
  # Test Database
  postgres_test:
    image: postgres:15-alpine
    container_name: antsss_test_db
    environment:
      POSTGRES_DB: antsss_tattoo_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54323:5432"
    volumes:
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  # Redis for testing
  redis_test:
    image: redis:7-alpine
    container_name: antsss_test_redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly no
    tmpfs:
      - /data

  # Elasticsearch for testing
  elasticsearch_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: antsss_test_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9201:9200"
    tmpfs:
      - /usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: antsss_test_network