name: 🐛 Bug Report
description: Report a bug to help us improve Antsss
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: I have provided all the required information below
          required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment did you encounter this bug in?
      options:
        - Production
        - Staging
        - Development/Local
        - Preview (PR deployment)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: What type of user were you when encountering this bug?
      options:
        - Client (looking for tattoos)
        - Artist
        - Studio Owner
        - Admin
        - Anonymous/Not logged in
      default: 0
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - 🔴 Critical (blocks core functionality)
        - 🟠 High (major feature broken)
        - 🟡 Medium (minor feature broken)
        - 🟢 Low (cosmetic/minor issue)
      default: 2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Mobile Chrome (Android)
        - Other
      default: 0

  - type: input
    id: browser_version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g. Chrome 120.0.0.0

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
      default: 0

  - type: input
    id: screen_size
    attributes:
      label: Screen Size/Resolution
      description: What's your screen size or resolution?
      placeholder: e.g. 1920x1080 or iPhone 14 Pro

  - type: textarea
    id: console_errors
    attributes:
      label: Console Errors
      description: Any errors shown in the browser console (F12 > Console)
      placeholder: Paste any console errors here
      render: javascript

  - type: textarea
    id: network_errors
    attributes:
      label: Network Errors
      description: Any failed network requests (F12 > Network tab)
      placeholder: List any failed API calls or network errors

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem
      placeholder: Drag and drop screenshots here or use the attach files button

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other information that might be helpful

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: How does this bug affect the application?
      options:
        - label: Prevents user registration/login
        - label: Blocks core booking functionality
        - label: Breaks payment processing
        - label: Causes data loss
        - label: Affects search/discovery
        - label: Mobile usability issues
        - label: Performance degradation
        - label: Visual/UI problems only

  - type: input
    id: workaround
    attributes:
      label: Workaround
      description: Is there a workaround for this issue?
      placeholder: Describe any temporary workaround if available

  - type: checkboxes
    id: volunteer
    attributes:
      label: Contribution
      description: Would you like to contribute to fixing this bug?
      options:
        - label: I'd be willing to submit a PR to fix this issue