name: ✨ Feature Request
description: Suggest a new feature or enhancement for Antsss
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨
        
        Please provide detailed information about your feature request to help us understand and prioritize it.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature doesn't already exist in the application
          required: true
        - label: I have thought about the implementation complexity
          required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - 🔍 Search & Discovery Enhancement
        - 📅 Booking System Improvement
        - 👤 User Profile Feature
        - 🎨 UI/UX Enhancement
        - 💳 Payment & Billing
        - 📱 Mobile Experience
        - 🔔 Notifications & Communication
        - 📊 Analytics & Reporting
        - 🛡️ Security & Privacy
        - 🔧 Admin Tools
        - 🚀 Performance Optimization
        - 🔌 Integration
        - 🌐 Accessibility
        - 📚 Other
      default: 0
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: Primary User Type
      description: Which user type would benefit most from this feature?
      options:
        - Client (looking for tattoos)
        - Artist
        - Studio Owner
        - Admin
        - All Users
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - 🔴 Critical (essential for core functionality)
        - 🟠 High (significantly improves user experience)
        - 🟡 Medium (nice to have improvement)
        - 🟢 Low (minor enhancement)
      default: 2
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or pain point this feature would address
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Write a user story for this feature
      placeholder: |
        As a [user type],
        I want to [action/capability],
        So that [benefit/value].
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. Use case 1: ...
        2. Use case 2: ...
        3. Use case 3: ...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: Add any visual mockups, wireframes, or design ideas
      placeholder: Drag and drop images here or describe the visual design

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: Describe any alternative approaches you've considered

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is to implement?
      options:
        - 🟢 Simple (few hours to 1 day)
        - 🟡 Medium (2-5 days)
        - 🟠 Complex (1-2 weeks)
        - 🔴 Very Complex (2+ weeks)
        - ❓ Unknown
      default: 4

  - type: checkboxes
    id: impact_areas
    attributes:
      label: Impact Areas
      description: Which parts of the application would this feature affect?
      options:
        - label: Frontend UI/UX
        - label: Backend API
        - label: Database schema
        - label: Authentication/Authorization
        - label: Payment processing
        - label: Search functionality
        - label: Mobile responsiveness
        - label: Performance
        - label: Security
        - label: Third-party integrations

  - type: textarea
    id: business_value
    attributes:
      label: Business Value
      description: What business value would this feature provide?
      placeholder: How would this feature benefit the business goals of Antsss?

  - type: textarea
    id: success_metrics
    attributes:
      label: Success Metrics
      description: How would you measure the success of this feature?
      placeholder: |
        - Metric 1: ...
        - Metric 2: ...
        - Metric 3: ...

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies
      description: Does this feature depend on other features or systems?
      options:
        - label: Requires new third-party service
        - label: Depends on other pending features
        - label: Requires database changes
        - label: Requires API changes
        - label: Requires design system updates
        - label: No dependencies

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, research, or examples
      placeholder: Any other information that would be helpful

  - type: input
    id: references
    attributes:
      label: References
      description: Links to similar features in other applications
      placeholder: https://example.com/similar-feature

  - type: checkboxes
    id: volunteer
    attributes:
      label: Contribution
      description: Would you like to contribute to implementing this feature?
      options:
        - label: I'd be willing to help with the design
        - label: I'd be willing to help with the implementation
        - label: I'd be willing to help with testing
        - label: I'd be willing to help with documentation